# Site settings
title: Batcher
description: "Batch Layer Processing and Export for GIMP 2.99.16"
baseurl: "/batcher"
url: "https://kamilburda.github.io"
repository: "kamilburda/batcher"
github_username: "{% include-config 'AUTHOR_NAME' %}"
copyright_years: "{% include-config 'COPYRIGHT_YEARS' %}"

plugin_name: "{% include-config 'PLUGIN_NAME' %}"
plugin_version: "{% include-config 'PLUGIN_VERSION' %}"
plugin_version_release_date: "{% include-config 'PLUGIN_VERSION_RELEASE_DATE' %}"
download_zip_suffix: ".zip"
sections_url: "/sections/"
license_remote_url: "blob/main/LICENSE"
license_local_filename: "LICENSE.txt"

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag

# Build settings
markdown: kramdown
is_release_build: false
