# Site settings
title: Export Layers
description: "GIMP plug-in that exports layers as separate images"
baseurl: "/gimp-plugin-export-layers"
url: "https://khalim19.github.io"
repository: "khalim19/gimp-plugin-export-layers"
github_username: "{% include-config 'AUTHOR_NAME' %}"
email: "{% include-config 'AUTHOR_CONTACT' %}"
copyright_years: "{% include-config 'COPYRIGHT_YEARS' %}"

plugin_name: "{% include-config 'PLUGIN_NAME' %}"
plugin_version: "{% include-config 'PLUGIN_VERSION' %}"
plugin_version_release_date: "{% include-config 'PLUGIN_VERSION_RELEASE_DATE' %}"
download_windows_suffix: "-windows.exe"
download_zip_suffix: ".zip"
sections_url: "/sections/"
license_remote_url: "blob/master/LICENSE"
license_local_filename: "LICENSE.txt"

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag

# Build settings
markdown: kramdown
is_release_build: false
