# Site settings
title: Batcher
description: "Batch layer processing and export plug-in for GIMP 3.0.0-RC1 and later."
baseurl: "/batcher"
url: "https://kamilburda.github.io"
repository: "kamilburda/batcher"
github_username: "{% include-config 'AUTHOR_NAME' %}"
copyright_years: "{% include-config 'COPYRIGHT_YEARS' %}"
permalink: /:categories/:year-:month-:day-:slug:output_ext
show_excerpts: true
excerpt_separator: "<!-- end of summary -->"
paginate: 10
paginate_path: "/news/:num/"

plugin_name: "{% include-config 'PLUGIN_NAME' %}"
plugin_version: "{% include-config 'PLUGIN_VERSION' %}"
plugin_version_release_date: "{% include-config 'PLUGIN_VERSION_RELEASE_DATE' %}"
download_zip_suffix: ".zip"
sections_url: "/sections/"
news_url: "/news/"
license_remote_url: "blob/main/LICENSE"
license_local_filename: "LICENSE.txt"

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown
is_release_build: false
